### ISSUE TITLE
UX Improvements

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/prof-viewer#25]
I found the Legion Prof viewer very difficult to use. The main dealbreaker for me was the lack of horizontal scroll. We support vertical scroll in the viewer, but not horizontal. The friction this creates while trying to diagnose performance issues is severe as I often want to zoom in on an area and then move back and forth side to side. 

Additional suggested improvements that are less crucial:

* Allow for the `ESC` key to clear pop-up boxes or selected things in the profile.
* Include the header for the directory where the profile logs are in the title text for the profiler window so users that are looking at multiple profiles simultaneously have some context.

All my observations come from running the viewer on a Mac M1 with the most recent Legion Prof in the control replication branch.

**Comment by elliottslaughter** [comment]
I think the immediate suggestions in this issue have been addressed?
