### ISSUE TITLE
Whole-word search results

### ISSUE THREAD

**Issue by bryevdv** [StanfordLegion/prof-viewer#31]
The current search matcher offers a string "contains" omde. There are some cases, e.g. searching for the legion id that is embedded inside a longer string, where a "contains" check may return more results than desired. An immediate solution for the legion id case (also be useful in general) would be to offer a "whole word boundary" search mode. 

cc @lightsighter

**Comment by elliottslaughter** [comment]
@lightsighter this is a generalization of the integer search we discussed in our meeting. We could think about more advanced search methods in the future, but for now I think this is the easiest way to implement a search that happens to do what you want, and may also be useful in other cases too.

**Comment by lightsighter** [comment]
Sounds fine to me. I'll take anything that lets me get all the boxes associated with a particular UID.
